version: "3.8"

services:

  idwly01: &idwly
    build: .
    command: flask run --host 0.0.0.0
    environment:
      FLASK_RUN_PORT: 8080
    restart: always
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '800M'

  idwly02:
    <<: *idwly
    environment:
      FLASK_RUN_PORT: 8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - idwly01
      - idwly02
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: contentdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'