CREATE TABLE IF NOT EXISTS CONTENT(
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(255),
    CATEGORY VARCHAR(255),
    DURATION INT,
    FORMAT VARCHAR(20),
    DESCRIPTION TEXT,
    BUSCA_FTS TSVECTOR GENERATED ALWAYS AS (
        TO_TSVECTOR('english', LOWER(COALESCE(NAME, '') || ' ' || COALESCE(DESCRIPTION, '')))
    ) STORED,

    PRIMARY KEY(ID)
);

CREATE INDEX IDX_DESC_CONTENT ON CONTENT USING GIN (BUSCA_FTS);

CREATE TABLE IF NOT EXISTS STORAGE(
    ID INT GENERATED ALWAYS AS IDENTITY,
    LOCAL_Y_N CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STORED_AT VARCHAR(255),
    CONTENT_ID INT,
    PRIMARY KEY(ID),
    CONSTRAINT fk_content FOREIGN KEY(CONTENT_ID) REFERENCES CONTENT(ID)
);

